when:
  branch: main
  event: [push, pull_request]

steps:
  install_engine_lib:
    image: maven:3.9.11-eclipse-temurin-21
    commands:
      - apt-get update && apt-get install -y git
      - cd /tmp
      - git clone https://github.com/Jastxz/engine-lib.git
      - cd engine-lib/engine-lib
      - mvn clean install -DskipTests
      - cd /tmp
      - git clone https://github.com/Jastxz/neural-lib.git
      - cd neural-lib
      - mvn clean install -DskipTests
      - cd /woodpecker/src/github.com/${CI_REPO}
      - mvn -B -ntp clean package -DskipTests

  build_push_image:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      USERNAME:
        from_secret: GHCR_USERNAME
      TOKEN:
        from_secret: GHCR_TOKEN
    commands:
      - export IMAGE="ghcr.io/$${USERNAME}/micro-neural:latest"
      - echo "$${TOKEN}" | docker login ghcr.io -u "$${USERNAME}" --password-stdin
      - docker build -t "$IMAGE" .
      - docker push "$IMAGE"

  deploy:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/serviciosjavi:/srv/serviciosjavi
    environment:
      USERNAME:
        from_secret: GHCR_USERNAME
      TOKEN:
        from_secret: GHCR_TOKEN
    commands:
      - cd /srv/serviciosjavi/microneural
      - echo "$${TOKEN}" | docker login ghcr.io -u "$${USERNAME}" --password-stdin
      - docker compose pull
      - docker compose up -d
